apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-httpsink.yaml
  - backstage.yaml
  - cm-app-config.yaml
  - cm-dyn-plugins.yaml
  - ns-httpsink.yaml
  - ns-setup-rhdh.yaml
  - pvc.yaml
  - secret-argocd.yaml
  - secret-gitlab.yaml
  - secret-keycloak.yaml
